# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:14:27+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import (
    Error,
    IndustriesGetResponse,
    JobFeedResponse,
    JobsPostRequest,
    JobTypesGetResponse,
    MajorProjectsGetResponse,
    RegionsGetResponse,
)

app = MCPProxy(
    description='This API allows you to receive a feed of jobs from WorkBC\'s Job Board. Please see our <a href="https://github.com/bcgov/api-specs/blob/master/COLLECTION_NOTICE.md#collection-notice" target="_blank">data collection notice</a>. Please note that you may experience issues when submitting requests to the delivery or test environment if using this [OpenAPI specification](https://github.com/bcgov/api-specs) in other API console viewers.',
    title='WorkBC Job Posting API',
    version='1.0.0',
    servers=[
        {'description': 'Production', 'url': 'https://workbcjobs.api.gov.bc.ca/v1'}
    ],
)


@app.get(
    '/Industries',
    description=""" The Industries endpoint returns all the Industries and related sub industries 
defined in WorkBC's Job Board. The response includes the id and caption for 
each industry and each sub industry.
 """,
    tags=['industry_data_handling', 'regional_information_services'],
)
def get__industries():
    """
    Industries
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/jobTypes',
    description=""" The Job Types endpoint returns details of all of the
job types defined in WorkBC's Job Board. The response includes the
id and caption.
 """,
    tags=['job_posting_operations'],
)
def get_job_types():
    """
    Job Types
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/jobs',
    description=""" The job feed endpoint returns an array of job records that satisfy the supplied criteria. """,
    tags=['job_posting_operations'],
)
def post_jobs(body: JobsPostRequest = None):
    """
    Job Feed
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/majorProjects',
    description=""" The Major Projects endpoint returns details of all of the
major projects defined in WorkBC's Job Board. The response includes the
id and caption.
 """,
    tags=['project_tracking'],
)
def get_major_projects():
    """
    Major Projects
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/regions',
    description=""" The Regions endpoint returns details of all of the
regions defined in WorkBC's Job Board. The response includes the
id and caption.
 """,
    tags=['regional_information_services'],
)
def get_regions():
    """
    Regions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
