# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:14:27+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Error(BaseModel):
    Message: Optional[str] = None


class JobTypeID(Enum):
    Undefined0 = 'Undefined0'
    Full_Time = 'Full-Time'
    Part_Time = 'Part-Time'
    Contract = 'Contract'
    Undefined4 = 'Undefined4'
    Undefined5 = 'Undefined5'
    Student = 'Student'
    Undefined7 = 'Undefined7'
    Undefined8 = 'Undefined8'
    Casual = 'Casual'
    Seasonal = 'Seasonal'
    Temporary = 'Temporary'
    Permanent = 'Permanent'
    Co_op = 'Co-op'
    Apprenticeship = 'Apprenticeship'


class MajorProject(BaseModel):
    Caption: Optional[str] = Field(None, description='The name of the Major Project.')
    ID: Optional[int] = Field(
        None,
        description='The unique ID of the Major Project in the WorkBC Job Board database. Use this when restricting the Job Feed to only one Major Project.',
    )


class RecordType(Enum):
    Undefined = 'Undefined'
    Update = 'Update'
    Delete = 'Delete'


class RegionID(Enum):
    Undefined = 'Undefined'
    Vancouver_Island_Coast = 'Vancouver Island/Coast'
    Mainland_Southwest = 'Mainland/Southwest'
    Thompson_Okanagan = 'Thompson-Okanagan'
    Kootenay = 'Kootenay'
    Cariboo = 'Cariboo'
    North_Coast = 'North Coast'
    Nechako = 'Nechako'
    Northeast = 'Northeast'


class SubIndustry(BaseModel):
    Caption: Optional[str] = Field(None, description='The name of the SubIndustries.')
    ID: Optional[int] = Field(None, description='Sub Industry ID.')


class City(Enum):
    Victoria = 'Victoria'
    Vancouver = 'Vancouver'


class JobTypes(Enum):
    integer__1_ = [1]
    integer__2_ = [2]


class LastRequestDate(Enum):
    field_2018_08_29T00_00_00_000Z = '2018-08-29T00:00:00.000Z'


class Region1(Enum):
    integer_1 = 1
    integer_2 = 2


class JobsPostRequest(BaseModel):
    city: Optional[City] = Field(
        'Victoria',
        description='The name of a city within B.C. Only job postings located within the specified city will be included in the response. If not specified, the data is not filtered by city.',
    )
    jobTypes: Optional[JobTypes] = Field(
        [1],
        description='ID values for types of job to filter on. Only job postings matching all specified values will be included in the response. If not specified, the data is not filtered by job type.',
    )
    lastRequestDate: Optional[LastRequestDate] = Field(
        '2018-08-29',
        description='The date of the last request. Only job postings changed or deleted after this time will be included in the response. Default is _today_ - 10 days.',
    )
    majorProjects: Optional[bool] = Field(
        True,
        description='When true, only include job postings that have a Major Project associated with them. When false, only include job postings that do not have a Major Project associated with them. If not specified, the data is not filtered by major project, unless the MajorProjectID parameter is used.',
    )
    region: Optional[Region1] = Field(
        1,
        description='The unique id of a region within B.C. Only job postings located within the specified region will be included in the response. If not specified, the data is not filtered by region',
    )


class MajorProjectsGetResponse(RootModel[List[MajorProject]]):
    root: List[MajorProject]


class Industry(BaseModel):
    Caption: Optional[str] = Field(None, description='The name of the Industries.')
    ID: Optional[int] = Field(None, description='Industry ID.')
    SubIndustries: Optional[List[SubIndustry]] = None


class JobType(BaseModel):
    Caption: Optional[str] = Field(None, description='The name of the Job Type.')
    ID: Optional[JobTypeID] = None


class Region(BaseModel):
    Caption: Optional[str] = Field(None, description='The name of the Region.')
    ID: Optional[RegionID] = None


class IndustriesGetResponse(RootModel[List[Industry]]):
    root: List[Industry]


class JobTypesGetResponse(RootModel[List[JobType]]):
    root: List[JobType]


class RegionsGetResponse(RootModel[List[Region]]):
    root: List[Region]


class Location(BaseModel):
    City: Optional[str] = Field(
        None, description='The name of the city where the job is located.'
    )
    Province: Optional[str] = Field(
        None, description='The name of the province where the job is located.'
    )
    RegionID: Optional[Region] = None
    RegionName: Optional[str] = Field(
        None, description='The name of the region in B.C. where the job is located.'
    )


class Job(BaseModel):
    EmployerName: Optional[str] = Field(
        None, description='The name of the employer who is offering the job.'
    )
    ExpiryDate: Optional[datetime] = Field(
        None,
        description="The date that the job will expire. It is the caller's responsibility to remove job postings once they expire. After this date the supplied Url will show a 404 page.",
    )
    JobDescription: Optional[str] = Field(
        None,
        description='Details of the job posting. This is limited to 250 characters, and HTML tags are stripped out. For a full description, use the Url property to view the job posting on the WorkBC website.',
    )
    JobID: Optional[int] = Field(
        None, description='The unique id of the job in the WorkBC Job Board database.'
    )
    JobTitle: Optional[str] = Field(None, description='The name of the job posting.')
    JobTypes: Optional[List[JobType]] = Field(
        None, description='The types of work associated with this job.'
    )
    Locations: Optional[List[Location]] = Field(
        None, description='Details of all of the locations where the job is available.'
    )
    MajorProject_1: Optional[MajorProject] = Field(None, alias='MajorProject')
    PostedDate: Optional[datetime] = Field(
        None, description='The date that the job was posted.'
    )
    RecordType_1: Optional[RecordType] = Field(None, alias='RecordType')
    SalaryMax: Optional[float] = None
    SalaryMin: Optional[float] = None
    SalaryMultiplier: Optional[int] = Field(
        None,
        description='The amount to multiply SalaryMin and SalaryMax by in order to convert to annual values. This is needed if you want to compare salaries for jobs that have been posted using different salary types.',
    )
    SalaryType: Optional[str] = None
    Url: Optional[str] = Field(
        None, description='The URL for the live job posting on the WorkBC website.'
    )


class JobFeedResponse(BaseModel):
    Jobs: Optional[List[Job]] = None
